AWSTemplateFormatVersion: '2010-09-09'
Description: FAKE SNS Topic for CodePipeline notifications


Resources:

  # FAKE NOTIFICATIONS TOPIC
  ########################################
  NotificationSNSTopic:
    Type: AWS::SNS::Topic
  
Outputs:
  NotificationSNSTopicArn:
    Value: !Ref 'NotificationSNSTopic'