AWSTemplateFormatVersion: '2010-09-09'
Description: FAKE CI Bucket


Resources:

  CiArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  
Outputs:
  CiArtifactBucket:
    Value: !Ref 'CiArtifactBucket'