export REACT_APP_ENABLE_ASSISTANCE="true"
export REACT_APP_PAGOPA_HELP_EMAIL="assistenza@pn.it"
export REACT_APP_SPID_CIE_ENTITY_ID="xx_servizicie_test"
export REACT_APP_SPID_TEST_ENV_ENABLED="true"
export REACT_APP_URL_API_LOGIN="https://hub-login.ecs.coll.pn.pagopa.it"
export REACT_APP_URL_FILE_PRIVACY_DISCLAIMER="#privacy-disclaimer"
export REACT_APP_URL_FILE_TERMS_AND_CONDITIONS="#terms-and-conditions"
