AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled


Outputs:
  BucketName:
    Value: !Ref ArtifactBucket


