AWSTemplateFormatVersion: '2010-09-09'
Description: 'Continuos Delivery pipeline for infrastructure deployment'
Parameters:
  
  ProjectName:
    Description: Usually "pn", can be changed for feature branch deployment
    Default: 'pn'
    Type: String
  
  EnvName:
    Description: 'dev, svil, test, coll, ...'
    Type: String
  

Resources:

  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "rate(10 minutes)"
      State: "ENABLED"
      RoleArn: !GetAtt "EventBusRunCodeBuildRole.Arn"
      Targets: 
        - Id: "TestRunner"
          RoleArn: !GetAtt "EventBusRunCodeBuildRole.Arn"
          Arn: 
            Fn::GetAtt: 
              - "RunTestsCodebuildProject"
              - "Arn"
          
  
  EventBusRunCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyName: runCodeBuild
          PolicyDocument:
            Statement:
              - Sid: startProjectRun
                Action:
                  - "codebuild:*"
                Effect: Allow
                Resource: 
                  - !GetAtt RunTestsCodebuildProject.Arn


  ###########################################################################
  ###  Utility that run e2e tests
  ###########################################################################
  RunTestsCodebuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub ${ProjectName}-RunE2eTestsCodeBuildProject
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source: 
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - echo "### NO PRE_BUILD"
            build:
              commands:
                - |
                  API_KEY=$( aws secretsmanager get-secret-value --secret-id secretsForTests | jq '.SecretString' | sed -e 's/^"//' -e 's/"$//' -e 's/\\"/"/g' | jq -r '.e2eTestApiKey' )
                - |
                  echo "### CLONE E2E TEST REPOSITORY ###"
                  echo "#####################"
                  git clone https://github.com/pagopa/pn-b2b-client.git
                  ( cd pn-b2b-client && echo "API_KEY=${API_KEY}" > config/application.properties )
                  ( cd pn-b2b-client && ./mvnw -Dpn.external.base-url=https://api.${ENV_NAME}.pn.pagopa.it '-Dpn.external.api-key=${API_KEY}'  clean verify )
          artifacts:
            files:
              - 'scripts/**/*'
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: "aws/codebuild/standard:5.0"
        EnvironmentVariables:
          - Name: REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
          - Name: ENV_NAME
            Type: PLAINTEXT
            Value: !Ref EnvName

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-e2e-CodeBuildRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: Allow
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  
  CodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${ProjectName}-e2e-CodeBuildPolicy
      Roles:
        - !Ref CodeBuildRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - "*"
            Resource:
              - "*"
