AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  PnCiCdTemplatesBucketName:
    Type: String
  BuildNum:
    Type: Number
    Default: 0

Resources:
  CodeArtifact:
    Type: AWS::CloudFormation::Stack
    Properties:
#      Tags:
#        - Key: BUILD_NUM
#          Value: !Ref BuildNum
      TemplateURL: !Sub 'https://${PnCiCdTemplatesBucketName}/infra/code-artifact.yaml'
      TimeoutInMinutes: 5

