AWSTemplateFormatVersion: '2010-09-09'
# see: https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-ECSbluegreen.html
Parameters:
  PnCiCdTemplatesBucket:
    Type: String
  BuildNum:
    Type: Number
    Default: 0

Resources:
  CodeArtifact:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BUILD_NUM : !Ref BuildNum
      Tags:
        - Key: BUILD_NUM
          Value: !Ref BuildNum
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucket}/code-artifact.yaml'
      TimeoutInMinutes: 5