AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  PnCiCdTemplatesBucketName:
    Type: String
    Description: Bucket name where pipeline copied the current version of CI templates
  CommitId:
    Type: String
    Default: 'none'
    Description: Git commit identifier

Resources:
  CodeArtifactStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: 'COMMIT_ID'
          Value: !Ref 'CommitId'
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/infra/code-artifact.yaml'
      TimeoutInMinutes: 5

  CiProjectStack:
   Type: AWS::CloudFormation::Stack
   Properties:
     Tags:
       - Key: 'COMMIT_ID'
         Value: !Ref 'CommitId'
     TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/build/ci-projects.yaml'
     Parameters:
       PnCiCdTemplatesBucketName: !Ref 'PnCiCdTemplatesBucketName'
     TimeoutInMinutes: 5

