AWSTemplateFormatVersion: '2010-09-09'
Description: Code Artifact and Artifact Bucket with export for CI/CD Pipeline
Parameters:
  PnCiCdTemplatesBucketName:
    Type: String
  CodeArtifactDomainName:
    Type: String
    Default: pn-codeartifact-domain
  CodeArtifactRepositoryName:
    Type: String
    Default: pn-codeartifact-repo
  CommitId:
    Type: String
    Default: none

Resources:
  ParentPomCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/build/mvn-jar-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-parent'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
      TimeoutInMinutes: 5
  PnModelCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/build/mvn-jar-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-model'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
      TimeoutInMinutes: 5
  PnCommonsCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/build/mvn-jar-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-commons'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
      TimeoutInMinutes: 5