AWSTemplateFormatVersion: '2010-09-09'
# see: https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-ECSbluegreen.html
Parameters:
  CodestarGitHubConnectionArn:
    Type: String
    Default: arn:aws:codestar-connections:eu-central-1:911845998067:connection/b28acf11-85de-478c-8ed2-2823f8c2a92d
  RepositoryName:
    Type: String
    Default: pagopa/pn-cicd
Resources:
  CodePipelineBucket:
    Type: AWS::S3::Bucket

  pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref 'CodePipelineBucket'
      RoleArn: !GetAtt 'PipelineRole.Arn'
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: ECR
              Configuration:
                RepositoryName:
                ImageTag: latest
              OutputArtifacts:
                - Name: imageDetail
              RunOrder: 1
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeployToECS
              Configuration:
                AppSpecTemplateArtifact: SourceArtifact
                ApplicationName: ecs-cd-application
                DeploymentGroupName: ecs-deployment-group
                Image1ArtifactName: MyImage
                Image1ContainerName: IMAGE1_NAME
                TaskDefinitionTemplatePath: taskdef.json
                AppSpecTemplatePath: appspec.yaml
                TaskDefinitionTemplateArtifact: SourceArtifact
              OutputArtifacts: []
              InputArtifacts:
                - Name: SourceArtifact
                - Name: MyImage
              Region: us-west-2
              Namespace: DeployVariables
              RunOrder: 2
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /