AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild for Glue jobs deployment

Parameters:
  GitHubProjectName:
    Description: Name of pagopa project
    Type: String
  
  GitHubDefaultBranch:
    Description: Name of the default github branch
    Type: String
    Default: main
  
  NotificationSNSTopic:
    Type: String
    Description: Topic for build and pipeline notification

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${GitHubProjectName}-glue-CodeBuild"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      BadgeEnabled: true
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: GITHUB_PRJ_NAME
            Type: PLAINTEXT
            Value: !Ref GitHubProjectName
          - Name: GIT_DEFAULT_BRANCH
            Type: PLAINTEXT
            Value: !Ref GitHubDefaultBranch
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/pagopa/${GitHubProjectName}'
        BuildSpec: |
          version: 0.2
          
          phases:
            pre_build:
              commands:
                - echo "Glue deployment started on $(date)"
                - export BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///'); export BRANCH_NAME=${BRANCH_NAME:=$GIT_DEFAULT_BRANCH}
                - echo "Branch: $BRANCH_NAME"
                
            build:
              commands:
                - echo "Uploading Glue scripts to S3..."
                - |
                  if [ -d "glue/scripts" ]; then
                    GLUE_BUCKET="aws-glue-assets-${AWS_ACCOUNT_ID}-${AWS_DEFAULT_REGION}"
                    echo "Target bucket: $GLUE_BUCKET"
                    
                    for script in glue/scripts/*.py; do
                      if [[ ! "$script" =~ _template\.py$ ]] && [[ ! "$script" =~ deploy-glue-jobs\.sh$ ]]; then
                        script_name=$(basename "$script")
                        echo "  Uploading ${script_name}..."
                        aws s3 cp "$script" "s3://${GLUE_BUCKET}/scripts/${GITHUB_PRJ_NAME}/${script_name}"
                      fi
                    done
                    
                    # Upload Glue libs
                    if [ -d "glue/libs" ] && [ "$(ls -A glue/libs)" ]; then
                      echo "Uploading Glue libs..."
                      for lib in glue/libs/*.py; do
                        lib_name=$(basename "$lib")
                        echo "  Uploading ${lib_name}..."
                        aws s3 cp "$lib" "s3://${GLUE_BUCKET}/libs/${GITHUB_PRJ_NAME}/${lib_name}"
                      done
                    fi
                    
                    echo "Glue scripts uploaded successfully!"
                  else
                    echo "No Glue scripts directory found"
                    exit 1
                  fi
                  
            post_build:
              commands:
                - echo "Glue deployment completed on $(date)"
      Artifacts:
        Type: NO_ARTIFACTS
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED,PULL_REQUEST_REOPENED
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Sub "^refs/heads/${GitHubDefaultBranch}$"

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${GitHubProjectName}-glue-CodeBuildRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${GitHubProjectName}-glue-*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::aws-glue-assets-${AWS::AccountId}-${AWS::Region}/*"
                  - !Sub "arn:aws:s3:::aws-glue-assets-${AWS::AccountId}-${AWS::Region}"
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: "*"

  BuildNotificationRule:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      Name: !Sub "${GitHubProjectName}-glue-build-notifications"
      DetailType: FULL
      Resource: !GetAtt CodeBuildProject.Arn
      EventTypeIds:
        - codebuild-project-build-state-failed
        - codebuild-project-build-state-succeeded
      Targets:
        - TargetType: SNS
          TargetAddress: !Ref NotificationSNSTopic

Outputs:
  CodeBuildProjectName:
    Description: CodeBuild project name
    Value: !Ref CodeBuildProject
  
  CodeBuildProjectArn:
    Description: CodeBuild project ARN
    Value: !GetAtt CodeBuildProject.Arn
