AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild for maven docker project
Parameters:
  GitHubProjectName:
    Description: Name of pagopa project name
    Type: String
  BaseDir:
    Description: base directory of the lambda project
    Type: String
  CiArtifactBucket:
    Description: Ci Artifact bucket name
    Type: String
  NotificationSNSTopic:
    Type: String
    Description: Topic for build and pipeline notification

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${GitHubProjectName}-${BaseDir}-CodeBuild"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Environment:
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        EnvironmentVariables:
          - Name: GITHUB_PRJ_NAME
            Type: PLAINTEXT
            Value: !Sub "${GitHubProjectName}"
          - Name: SUB_PRJ_NAME
            Type: PLAINTEXT
            Value: !Sub "${BaseDir}"
          - Name: CI_BUCKET_NAME
            Type: PLAINTEXT
            Value: !Sub "${CiArtifactBucket}"
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/pagopa/${GitHubProjectName}'
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              on-failure: ABORT
              commands:
                - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///'); export BRANCH_NAME=${!BRANCH_NAME:=$GIT_DEFAULT_BRANCH}
                - export BRANCH_TARGET=$(echo $CODEBUILD_WEBHOOK_BASE_REF | sed 's/refs\/heads\///')
                - export PR_NUM=$(echo $CODEBUILD_SOURCE_VERSION | sed 's/pr\///')
                - export CI_PROFILE="$CODEBUILD_CI"
                - cd $SUB_PRJ_NAME
            build:
              on-failure: ABORT
              commands:
                - echo Build started on `date`
                - npm run-script test-build
            post_build:
              on-failure: ABORT
              commands:
                - aws s3 cp function.zip "s3://$CI_BUCKET_NAME/$GITHUB_PRJ_NAME/$BRANCH_NAME/$SUB_PRJ_NAME.zip"
      Artifacts:
        Type: NO_ARTIFACTS
      TimeoutInMinutes: 10
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH, PULL_REQUEST_MERGED
            - Type: HEAD_REF
              Pattern: ^refs/heads/(main|develop)$
#          - - Type: EVENT
#              Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED
#            - Type: BASE_REF
#              Pattern: ^refs/heads/(main|develop)$

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CodeBuildReportGroup
                Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Resource:
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*'
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "*"
              - Sid: BearerTokenPolicy
                Effect: Allow
                Action:
                  - sts:GetServiceBearerToken
                Resource: "*"
                Condition:
                  StringEquals:
                    'sts:AWSServiceName': codeartifact.amazonaws.com
              - Sid: GitHubSecret
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "*"
              - Sid: CiArtifactBucket
                Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${CiArtifactBucket}'
              - Sid: CiArtifactBucketObjects
                Effect: Allow
                Action:
                  - s3:GetObjectVersion
                  - s3:GetObjectVersionAcl
                  - 's3:PutObject*'
                Resource:
                  - !Sub 'arn:aws:s3:::${CiArtifactBucket}/*'

  CodeBuildNotifications:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      DetailType: FULL
      Name: !Sub '${GitHubProjectName}-CI'
      EventTypeIds:
        - codebuild-project-build-state-failed
      Resource: !Sub '${CodeBuildProject.Arn}'
      Targets:
        - TargetAddress: !Ref 'NotificationSNSTopic'
          TargetType: SNS