AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild for maven docker project
Parameters:
  GitHubProjectName:
    Description: Name of pagopa project name pattern = [A-Za-z0-9][A-Za-z0-9\-_]{1,122}
    Type: String
  GitHubDefaultBranch:
    Description: Name of the dafult github branch
    Type: String
    Default: main    
  BaseDir:
    Description: base directory of the lambdas = [A-Za-z0-9][A-Za-z0-9\-_]{123,240}
    Type: String
  BaseDirEscaped:
    Description: base directory of the lambdas = [A-Za-z0-9][A-Za-z0-9\-_]{123,240}
    Type: String
  CiArtifactBucket:
    Description: Ci Artifact bucket name
    Type: String
  NotificationSNSTopic:
    Type: String
    Description: Topic for build and pipeline notification
  NodeVersion:
    Type: String
    Default: '22'
    AllowedValues:
      - '20'
      - '22'
    Description: Node.js runtime version to use

Conditions:
  RequiresNode22: !Equals [ !Ref NodeVersion, '22' ]

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${GitHubProjectName}-${BaseDirEscaped}-CodeBuild"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      BadgeEnabled: true
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !If [ RequiresNode22, aws/codebuild/standard:7.0, aws/codebuild/standard:6.0 ]
        EnvironmentVariables:
          - Name: GITHUB_PRJ_NAME
            Type: PLAINTEXT
            Value: !Sub "${GitHubProjectName}"
          - Name: FUNCTIONS_FOLDER_NAME
            Type: PLAINTEXT
            Value: !Sub "${BaseDir}"
          - Name: GIT_DEFAULT_BRANCH
            Type: PLAINTEXT
            Value: !Sub "${GitHubDefaultBranch}"
          - Name: CI_BUCKET_NAME
            Type: PLAINTEXT
            Value: !Sub "${CiArtifactBucket}"
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/pagopa/${GitHubProjectName}'
        BuildSpec: |
          version: 0.2
          env:
            shell: bash
            secrets-manager:
              SONAR_TOKEN: arn:aws:secretsmanager:eu-central-1:911845998067:secret:SonarCloud-7370vM:token
          phases:
            pre_build:
              on-failure: ABORT
              commands:
                - export CODEBUILD_GIT_MESSAGE="$(git log -1 --pretty=%B)"
                - export CODEBUILD_GIT_AUTHOR="$(git log -1 --pretty=%an)"
                - export CODEBUILD_GIT_AUTHOR_EMAIL="$(git log -1 --pretty=%ae)"
                - export CODEBUILD_GIT_COMMIT="$(git log -1 --pretty=%H)"
                - echo "CODEBUILD_WEBHOOK_HEAD_REF=$CODEBUILD_WEBHOOK_HEAD_REF"
                - echo "CODEBUILD_WEBHOOK_BASE_REF=$CODEBUILD_WEBHOOK_BASE_REF"
                - echo "CODEBUILD_SOURCE_VERSION=$CODEBUILD_SOURCE_VERSION"
                - echo "GIT_DEFAULT_BRANCH=$GIT_DEFAULT_BRANCH"
                - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///'); export BRANCH_NAME=${BRANCH_NAME:=$GIT_DEFAULT_BRANCH}
                - if echo $CODEBUILD_SOURCE_VERSION | grep -q ^pr/ ; then PR_NUM=$(echo $CODEBUILD_SOURCE_VERSION | sed 's/pr\///'); BRANCH_TARGET=$(echo $CODEBUILD_WEBHOOK_BASE_REF | sed 's/refs\/heads\///'); export PR_NUM BRANCH_TARGET; fi;
                - export CI_PROFILE="$CODEBUILD_CI"
                - |
                  if ( [ -z "${PR_NUM}" ] ) then
                    export PR_NUM=$(curl -L \
                      -H "Accept: application/vnd.github+json" \
                      -H "X-GitHub-Api-Version: 2022-11-28" \
                      "https://api.github.com/repos/pagopa/${GITHUB_PRJ_NAME}/pulls?state=all&sort=updated&direction=desc&head=pagopa:${BRANCH_NAME}" | jq -r '.[] | .number ' | head -1)

                    echo "EXPORTING PR_NUM=${PR_NUM}"
                  fi
                - |
                  if ( [ ! -z "${PR_NUM}" ] ) then
                    export BRANCH_TARGET=$(curl -L \
                      -H "Accept: application/vnd.github+json" \
                      -H "X-GitHub-Api-Version: 2022-11-28" \
                      "https://api.github.com/repos/pagopa/${GITHUB_PRJ_NAME}/pulls/${PR_NUM}" | jq '.base.ref')
                    echo "BRANCH_TARGET=${BRANCH_TARGET}"
                  fi
            build:
              on-failure: ABORT
              commands:
                - cd $FUNCTIONS_FOLDER_NAME
                - echo Build started on `date`
                - |
                  for i in */
                  do
                    echo "Bulding $i"
                    cd $i
                    npm ci
                    npm run-script test-build || exit 1
                    cd ..
                  done               
            post_build:
              on-failure: ABORT
              commands:
                - export COMMIT_ID=$(git rev-parse --verify HEAD)
                - echo $COMMIT_ID > commitID.txt
                - |
                  for i in *
                  do
                    if [[ -f "${i}/function.zip" ]]
                    then
                      cp -p "${i}/function.zip" "${i}.zip" 
                    fi
                    if [[ -f "${i}/code_layer.zip" ]]
                    then
                      cp -p "${i}/code_layer.zip" "${i}_code.zip" 
                    fi
                    if [[ -f "${i}/lib_layer.zip" ]]
                    then
                      cp -p "${i}/lib_layer.zip" "${i}_libs.zip"
                    fi
                  done 
                - zip -u functions.zip commitID.txt *.zip
                - aws s3 cp functions.zip "s3://$CI_BUCKET_NAME/$GITHUB_PRJ_NAME/$BRANCH_NAME/functions.zip"
                - aws s3 cp functions.zip "s3://$CI_BUCKET_NAME/$GITHUB_PRJ_NAME/commits/$COMMIT_ID/functions.zip"
                - |
                  if [[ "$BRANCH_NAME" =~ ^(main|develop)|release\/.* ]]; then
                    echo Generate build event
                    EVENT_DETAIL="{ \"event_type\": \"BUILD_DONE\", \"project_branch\":\"${BRANCH_NAME}\",\"project_type\":\"LAMBDA_SET\", \"project\":\"${GITHUB_PRJ_NAME}\", \"commit_id\": \"${COMMIT_ID}\" }"
                    echo $EVENT_DETAIL | jq -R -s '[{ "DetailType": "CiEvent","EventBusName": "CiEventBus", "Source":"Builder", "Detail": . }]' > ci_event.json
                    cat ci_event.json
                    aws events put-events --entries file://ci_event.json
                  fi
      Artifacts:
        Type: NO_ARTIFACTS
      TimeoutInMinutes: 10
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH, PULL_REQUEST_MERGED
            - Type: HEAD_REF
              Pattern: ^refs/heads/(main|develop)|(feature|hotfix|bug|release)\/.+$
            #- Type: FILE_PATH
            #  Pattern: !Sub "^${BaseDir}/.*"
          # - - Type: EVENT
          #     Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED
          #   - Type: BASE_REF
          #     Pattern: ^refs/heads/(main|develop)|release\/.*$
          #   - Type: FILE_PATH
          #     Pattern: !Sub "^${BaseDir}/.*"

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CodeBuildReportGroup
                Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Resource:
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*'
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "*"
              - Sid: BearerTokenPolicy
                Effect: Allow
                Action:
                  - sts:GetServiceBearerToken
                Resource: "*"
                Condition:
                  StringEquals:
                    'sts:AWSServiceName': codeartifact.amazonaws.com
              - Sid: SonarCloudTokenSecret
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "arn:aws:secretsmanager:eu-central-1:911845998067:secret:SonarCloud-7370vM"
              - Sid: CiArtifactBucket
                Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${CiArtifactBucket}'
              - Sid: CiArtifactBucketObjects
                Effect: Allow
                Action:
                  - s3:GetObjectVersion
                  - s3:GetObjectVersionAcl
                  - 's3:PutObject*'
                Resource:
                  - !Sub 'arn:aws:s3:::${CiArtifactBucket}/*'
              - Sid: SendBuildEvents
                Effect: Allow
                Action:
                  - events:PutEvents
                Resource:
                  - !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/CiEventBus'

  CodeBuildNotifications:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      DetailType: FULL
      Name: !Sub '${GitHubProjectName}-${BaseDirEscaped}-CI'
      EventTypeIds:
        - codebuild-project-build-state-failed
      Resource: !Sub '${CodeBuildProject.Arn}'
      Targets:
        - TargetAddress: !Ref 'NotificationSNSTopic'
          TargetType: SNS
