export REACT_APP_URL_API="https://webapi.dev.pn.pagopa.it/"
export REACT_APP_CHECKOUT_URL="https://uat.checkout.pagopa.it"
export REACT_APP_PAGOPA_HELP_EMAIL="pn.dev@assistenza.pagopa.it"
export REACT_APP_PAYMENT_DISCLAIMER_URL="https://www.pagopa.it"
export REACT_APP_URL_FE_LOGIN="https://portale-login.dev.pn.pagopa.it"
export REACT_APP_DISABLE_INACTIVITY_HANDLER="true"
export REACT_APP_MIXPANEL_TOKEN="DUMMY"
export REACT_APP_ONETRUST_DOMAIN_ID="fd5aef6f-a6d3-422b-87b7-aa5e2cb6510c"
