AWSTemplateFormatVersion: 2010-09-09
Description: 'This template deploys an EventBridge Rule and CloudWatch alarm to monitor vulnerabilities in ECR images'

Parameters:
  AlarmSNSTopicArn:
    Type: String
    Description: ARN of the SNS Topic for CloudWatch Alarms

Resources:

  # Rule triggered when a Critical Vulnerabilities is detected by the ECR Scan
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: "ECRCriticalVulnerabilitiesDetected"
      Description: Triggered when Critical Vulnerabilities are detected when an ECR image is scanned
      EventPattern: |
        {
          "source": ["aws.ecr"],
          "detail-type": ["ECR Image Scan"],
          "detail": {
            "scan-status": ["COMPLETE"],
            "finding-severity-counts": {
              "CRITICAL": [{
                "numeric": [">", 0]
              }]
            }
          }
        }
      State: ENABLED
      Targets:
        - Arn: !GetAtt LogGroupRuleTarget.Arn
          Id: LogTarget

  # Log Group Target of the Event Bridge Rule
  LogGroupRuleTarget:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/events/ecr-critical-vulnerabilities"
      RetentionInDays: 14
  
  LogGroupRuleTargetPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: "EventBridgeToCWLogsPolicy"
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "EventBridgetoCWLogsCreateLogStreamPolicy",
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "events.amazonaws.com"
                ]
              },
              "Action": [
                "logs:CreateLogStream"
              ],
              "Resource": [
                "${LogGroupRuleTarget.Arn}"
              ]
            },
            {
              "Sid": "EventBridgetoCWLogsPutLogEventsPolicy",
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "events.amazonaws.com"
                ]
              },
              "Action": [
                "logs:PutLogEvents"
              ],
              "Resource": [
                "${LogGroupRuleTarget.Arn}"
              ],
              "Condition": {
                "ArnEquals": {"AWS:SourceArn": "${EventRule.Arn}"}
              }
            }
          ]
        }

  # Metric based on logs arriving in the log group
  LogsMetricFilter: 
    Type: AWS::Logs::MetricFilter
    Properties: 
      LogGroupName: !Ref LogGroupRuleTarget
      FilterPattern: ""
      MetricTransformations: 
        - MetricValue: 1
          MetricNamespace: ECRVulnerabilities
          MetricName: ImageCriticalVulnerabilities

  # Alarm based on the Metric Filter
  ECRAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:  "ECR-Critical-Vulnerabilities"
      AlarmDescription: "CloudWatch alarm for ECR Critical Vulnerabilities detected"
      TreatMissingData: notBreaching        
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: 1            
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      Period: 60
      Namespace: ECRVulnerabilities   
      MetricName: ImageCriticalVulnerabilities
      Statistic: Sum
      Threshold: 1