AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild for maven docker project
Parameters:
  EcrName:
    Description: Name of Ecr
    Type: String
    Default: pn-delivery

  AllowedDeployAccount1:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount2:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount3:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount4:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount5:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount6:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount7:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount8:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount9:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount10:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount11:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount12:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount13:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount14:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount15:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount16:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount17:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount18:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount19:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount20:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount21:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount22:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount23:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount24:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount25:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount26:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount27:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount28:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount29:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount30:
    Type: Number
    Description: Account number allowed to read the artifacts
Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      RepositoryName: !Sub '${EcrName}'
      RepositoryPolicyText: !Sub '{
            "Version": "2008-10-17",
            "Statement": [
              {
                "Sid": "Allow cicd",
                "Effect": "Allow",
                "Principal": {
                  "AWS": [ 
                    "arn:aws:iam::${AllowedDeployAccount1}:root",
                    "arn:aws:iam::${AllowedDeployAccount2}:root",
                    "arn:aws:iam::${AllowedDeployAccount3}:root",
                    "arn:aws:iam::${AllowedDeployAccount4}:root",
                    "arn:aws:iam::${AllowedDeployAccount5}:root",
                    "arn:aws:iam::${AllowedDeployAccount6}:root",
                    "arn:aws:iam::${AllowedDeployAccount7}:root",
                    "arn:aws:iam::${AllowedDeployAccount8}:root",
                    "arn:aws:iam::${AllowedDeployAccount9}:root",
                    "arn:aws:iam::${AllowedDeployAccount10}:root",
                    "arn:aws:iam::${AllowedDeployAccount11}:root",
                    "arn:aws:iam::${AllowedDeployAccount12}:root",
                    "arn:aws:iam::${AllowedDeployAccount13}:root",
                    "arn:aws:iam::${AllowedDeployAccount14}:root",
                    "arn:aws:iam::${AllowedDeployAccount15}:root",
                    "arn:aws:iam::${AllowedDeployAccount16}:root",
                    "arn:aws:iam::${AllowedDeployAccount17}:root",
                    "arn:aws:iam::${AllowedDeployAccount18}:root",
                    "arn:aws:iam::${AllowedDeployAccount19}:root",
                    "arn:aws:iam::${AllowedDeployAccount20}:root",
                    "arn:aws:iam::${AllowedDeployAccount21}:root",
                    "arn:aws:iam::${AllowedDeployAccount22}:root",
                    "arn:aws:iam::${AllowedDeployAccount23}:root",
                    "arn:aws:iam::${AllowedDeployAccount24}:root",
                    "arn:aws:iam::${AllowedDeployAccount25}:root",
                    "arn:aws:iam::${AllowedDeployAccount26}:root",
                    "arn:aws:iam::${AllowedDeployAccount27}:root",
                    "arn:aws:iam::${AllowedDeployAccount28}:root",
                    "arn:aws:iam::${AllowedDeployAccount29}:root",
                    "arn:aws:iam::${AllowedDeployAccount30}:root"
                  ]
                },
                "Action": [
                  "ecr:BatchCheckLayerAvailability",
                  "ecr:BatchGetImage",
                  "ecr:DescribeImages",
                  "ecr:DescribeRepositories",
                  "ecr:GetDownloadUrlForLayer",
                  "ecr:ListImages"
                ]
              }
            ]
          }'
