AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EventBridge rule 'reRouteToMilan'
Resources:
  
  SendCompilationEventsToOldEnvsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Reroute CI events to Old Dev Env
      EventBusName: CiEventBus
      EventPattern:
        source:
          - prefix: ''
        detail:
          project: [ { "anything-but": [ "pn-infra-core", "pn-infra-confinfo" ] } ]
      Name: reRouteToNewOldEnvs
      State: DISABLED
      Targets:
        # Disattivo hotfix
        #- Id: Id1b845a56-fc19-40ab-a435-9cfaaf2c657c
        #  Arn: arn:aws:events:eu-south-1:804103868123:event-bus/CdEventBus
        #  RoleArn: >-
        #    arn:aws:iam::911845998067:role/service-role/Amazon_EventBridge_Invoke_Event_Bus_1098279274
        #- Id: Id96cf4d8e-5855-4280-9732-30d1ca66d6b2
        #  Arn: arn:aws:events:eu-south-1:118759374619:event-bus/CdEventBus
        #  RoleArn: >-
        #    arn:aws:iam::911845998067:role/service-role/Amazon_EventBridge_Invoke_Event_Bus_1952238975
        - Id: OldDevCore
          Arn: arn:aws:events:eu-south-1:558518206506:event-bus/CdEventBus
          RoleArn: !GetAtt SendCompilationEventsRuleRole.Arn
        - Id: OldDevConfinfo
          Arn: arn:aws:events:eu-south-1:946373734005:event-bus/CdEventBus
          RoleArn: !GetAtt SendCompilationEventsRuleRole.Arn

  SendCompilationEventsToNewEnvsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Reroute CI events to New Dev Env
      EventBusName: CiEventBus
      EventPattern:
        source:
          - prefix: ''
      Name: reRouteToNewNewEnvs
      State: ENABLED
      Targets:
        - Id: NewDevCore
          Arn: arn:aws:events:eu-south-1:089813480515:event-bus/CdEventBus
          RoleArn: !GetAtt SendCompilationEventsRuleRole.Arn
        - Id: NewDevConfinfo
          Arn: arn:aws:events:eu-south-1:830192246553:event-bus/CdEventBus
          RoleArn: !GetAtt SendCompilationEventsRuleRole.Arn


  SendCompilationEventsRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service: 
                - 'events.amazonaws.com'
      Policies:
        - PolicyName: 'PutEventsInlinePolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Sid: 'PutEventsOnTargetAccount'
                Effect: Allow
                Action:
                  - 'events:PutEvents'
                Resource:
                  - arn:aws:events:eu-south-1:089813480515:event-bus/CdEventBus
                  - arn:aws:events:eu-south-1:830192246553:event-bus/CdEventBus
                  - arn:aws:events:eu-south-1:946373734005:event-bus/CdEventBus
                  - arn:aws:events:eu-south-1:558518206506:event-bus/CdEventBus

