AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Genera il repository maven e include gli stack di generazione dei CodeBuild project per 
  effettuare il build di librerie, microservizi e webapp.

Parameters:
  PnCiCdTemplatesBucketName:
    Type: String
    Description: Bucket name where pipeline copied the current version of CI templates
  CodeArtifactDomainName:
    Type: String
    Default: pn-codeartifact-domain
  CodeArtifactRepositoryName:
    Type: String
    Default: pn-codeartifact-repo
  NotificationSNSTopic:
    Type: String
    Default: 'none'
    Description: Topic for build and pipeline notification
  
  AllowedDeployAccount1:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount2:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount3:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount4:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount5:
    Type: Number
    Description: Account number allowed to read the artifacts


Resources:
  CodeArtifactStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/infra/code-artifact.yaml'
      Parameters:
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
      TimeoutInMinutes: 5

  CiArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
  
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CiArtifactBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${CiArtifactBucket}
              - !Sub arn:aws:s3:::${CiArtifactBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AllowedDeployAccount1}:root
                - !Sub arn:aws:iam::${AllowedDeployAccount2}:root
                - !Sub arn:aws:iam::${AllowedDeployAccount3}:root
                - !Sub arn:aws:iam::${AllowedDeployAccount4}:root
                - !Sub arn:aws:iam::${AllowedDeployAccount5}:root

# Progetti CI jar
  ParentPomCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/mvn-jar-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-parent'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
      TimeoutInMinutes: 5
  PnModelCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/mvn-jar-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-model'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
      TimeoutInMinutes: 5
  PnCommonsCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/mvn-jar-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-commons'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
      TimeoutInMinutes: 5
# Progetti docker
  PnDeliveryCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/mvn-docker-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-delivery'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
        GitHubDefaultBranch: 'develop'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
        AllowedDeployAccount1: !Ref AllowedDeployAccount1
        AllowedDeployAccount2: !Ref AllowedDeployAccount2
        AllowedDeployAccount3: !Ref AllowedDeployAccount3
        AllowedDeployAccount4: !Ref AllowedDeployAccount4
        AllowedDeployAccount5: !Ref AllowedDeployAccount5
      TimeoutInMinutes: 5
  PnDeliveryPushCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/mvn-docker-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-delivery-push'
        GitHubDefaultBranch: 'develop'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
        AllowedDeployAccount1: !Ref AllowedDeployAccount1
        AllowedDeployAccount2: !Ref AllowedDeployAccount2
        AllowedDeployAccount3: !Ref AllowedDeployAccount3
        AllowedDeployAccount4: !Ref AllowedDeployAccount4
        AllowedDeployAccount5: !Ref AllowedDeployAccount5
      TimeoutInMinutes: 5
  PnExternalChannelsCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/mvn-docker-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-external-channels'
        GitHubDefaultBranch: 'develop'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
        AllowedDeployAccount1: !Ref AllowedDeployAccount1
        AllowedDeployAccount2: !Ref AllowedDeployAccount2
        AllowedDeployAccount3: !Ref AllowedDeployAccount3
        AllowedDeployAccount4: !Ref AllowedDeployAccount4
        AllowedDeployAccount5: !Ref AllowedDeployAccount5
      TimeoutInMinutes: 5
  PnDataVaultCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/mvn-docker-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-data-vault'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
        AllowedDeployAccount1: !Ref AllowedDeployAccount1
        AllowedDeployAccount2: !Ref AllowedDeployAccount2
        AllowedDeployAccount3: !Ref AllowedDeployAccount3
        AllowedDeployAccount4: !Ref AllowedDeployAccount4
        AllowedDeployAccount5: !Ref AllowedDeployAccount5
      TimeoutInMinutes: 5
  PnExternalRegistriesCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/mvn-docker-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-external-registries'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
        AllowedDeployAccount1: !Ref AllowedDeployAccount1
        AllowedDeployAccount2: !Ref AllowedDeployAccount2
        AllowedDeployAccount3: !Ref AllowedDeployAccount3
        AllowedDeployAccount4: !Ref AllowedDeployAccount4
        AllowedDeployAccount5: !Ref AllowedDeployAccount5
      TimeoutInMinutes: 5
  PnMandateCI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/mvn-docker-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-mandate'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
        AllowedDeployAccount1: !Ref AllowedDeployAccount1
        AllowedDeployAccount2: !Ref AllowedDeployAccount2
        AllowedDeployAccount3: !Ref AllowedDeployAccount3
        AllowedDeployAccount4: !Ref AllowedDeployAccount4
        AllowedDeployAccount5: !Ref AllowedDeployAccount5
      TimeoutInMinutes: 5
# Progetti Lambda
  PnApikeyAuthorizerLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/nodejs-lambda-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-auth-fleet'
        BaseDir: 'apikeyAuthorizer'
        CiArtifactBucket: !Ref 'CiArtifactBucket'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
      TimeoutInMinutes: 5
  PnJwtAuthorizerLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/nodejs-lambda-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-auth-fleet'
        BaseDir: 'jwtAuthorizer'
        CiArtifactBucket: !Ref 'CiArtifactBucket'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
      TimeoutInMinutes: 5
  PnTokenExchangeLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/nodejs-lambda-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-auth-fleet'
        BaseDir: 'tokenExchange'
        CiArtifactBucket: !Ref 'CiArtifactBucket'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
      TimeoutInMinutes: 5

  # Progetti WebApp
  PnWebapp:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/npm-webapp-codebuild.yaml'
      Parameters:
        GitHubProjectName: 'pn-webapp'
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
        CiArtifactBucket: !Ref 'CiArtifactBucket'
        NotificationSNSTopic: !Ref 'NotificationSNSTopic'
      TimeoutInMinutes: 5

Outputs:
  CiArtifactBucket:
    Value: !Ref 'CiArtifactBucket'
